# Site settings
title: Lawrence Holmes
email: holmes.lr@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Bournemouth University student studying Digital Media Design,
  currently on placement at digitalSHIFT.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "lrholmes.github.io" # the base hostname & protocol for your site
twitter_username: lawrence
github_username:  lrholmes

collections:
  projects:
    output: true
    permalink: /projects/:path/

# Build settings
markdown: kramdown
